//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTUDQL2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputInfo
    {
        public int Id { get; set; }
        public int IdObject { get; set; }
        public System.DateTime DateInput { get; set; }
        public string Status { get; set; }
        public decimal PriceInput { get; set; }
        public decimal PriceOutput { get; set; }
    }
}
