//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTUDQL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public int IdUnit { get; set; }
        public int IdKind { get; set; }
        public int IdSuplier { get; set; }
        public System.TimeSpan Length { get; set; }
        public string View { get; set; }
    }
}
